[package]
name = "uniproc-linux-agent-ebpf"
version = "0.1.0"
edition.workspace = true

[build-dependencies]
libbpf-cargo = "0.26.0"

[profile.dev]
debug = true

[[bin]]
name = "uniproc-linux-agent"
path = "src/main.rs"
